=begin
#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ProductsAttributesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProductsAttributesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ProductsAttributesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProductsAttributesApi' do
    it 'should create an instance of ProductsAttributesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ProductsAttributesApi)
    end
  end

  # unit tests for add_products_attributes
  # 
  # Creates a new attribute of products in the store.
  # @param attribute Attribute to add to the store
  # @param [Hash] opts the optional parameters
  # @return [Array<Attribute>]
  describe 'add_products_attributes test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_product_attribute_by_id
  # 
  # deletes a single attribute of products based on the ID supplied
  # @param id ID of attribute to delete
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_product_attribute_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_product_attribute_by_id
  # 
  # Returns a attribute of products based on a single ID  ### Includes You can give the following values on includes parameter: &#x60;options&#x60; 
  # @param id ID of attribute to fetch
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :includes Include associated objects within response
  # @return [Attribute]
  describe 'get_product_attribute_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_products_attributes
  # 
  # Returns all attributes of products from the system that the user has access to  ### Includes You can give the following values on includes parameter: &#x60;options&#x60; 
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :includes Include associated objects within response
  # @option opts [Integer] :limit max records to return
  # @option opts [Array<String>] :order_by Specify the field to be sorted, examples:  - &#x60;?order_by&#x3D;id|desc&#x60; - &#x60;?order_by&#x3D;updated_at|desc,position|asc&#x60; 
  # @return [Array<Attribute>]
  describe 'get_products_attributes test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_product_attribute_by_id
  # 
  # update a single attribute of products based on the ID supplied
  # @param id ID of attribute to update
  # @param product_attribute Attribute to add to the store
  # @param [Hash] opts the optional parameters
  # @return [Attribute]
  describe 'update_product_attribute_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
