=begin
#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ShippingsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ShippingsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ShippingsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ShippingsApi' do
    it 'should create an instance of ShippingsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ShippingsApi)
    end
  end

  # unit tests for add_shipping
  # 
  # Creates a new shipping in the store.
  # @param shipping Shipping to add to the store
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2013]
  describe 'add_shipping test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_shipping_by_id
  # 
  # deletes a single shipping based on the ID supplied
  # @param id ID of shipping to delete
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_shipping_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_shipping_by_id
  # 
  # Returns a shipping based on a single ID
  # @param id ID of shipping to fetch
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit max records to return
  # @return [InlineResponse2013]
  describe 'get_shipping_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_shippings
  # 
  # Returns all shippings from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :includes Include associated objects within response
  # @option opts [Integer] :limit max records to return
  # @option opts [Array<String>] :order_by Specify the field to be sorted, examples:  - &#x60;?order_by&#x3D;id|desc&#x60; - &#x60;?order_by&#x3D;updated_at|desc,position|asc&#x60; 
  # @return [InlineResponse2003]
  describe 'get_shippings test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_shipping_by_id
  # 
  # update a single shipping based on the ID supplied
  # @param id ID of shipping to update
  # @param tax Shipping to update in store
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2013]
  describe 'update_shipping_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_shipping_by_id_0
  # 
  # update a single shipping based on the ID supplied
  # @param id ID of shipping to update
  # @param tax Shipping to update in store
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2013]
  describe 'update_shipping_by_id_0 test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
