=begin
#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::TaxesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TaxesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::TaxesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TaxesApi' do
    it 'should create an instance of TaxesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::TaxesApi)
    end
  end

  # unit tests for add_taxes
  # 
  # Creates a new tax in the store.
  # @param tax Tax to add to the store
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2012]
  describe 'add_taxes test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_tax_by_id
  # 
  # deletes a single tax based on the ID supplied
  # @param id ID of tax to delete
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_tax_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_tax_by_id
  # 
  # Returns a tax based on a single ID
  # @param id ID of tax to fetch
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit max records to return
  # @return [InlineResponse2012]
  describe 'get_tax_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_taxes
  # 
  # Returns all taxes from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :includes Include associated objects within response
  # @option opts [Integer] :limit max records to return
  # @option opts [Array<String>] :order_by Specify the field to be sorted, examples:  - &#x60;?order_by&#x3D;id|desc&#x60; - &#x60;?order_by&#x3D;updated_at|desc,position|asc&#x60; 
  # @return [InlineResponse2002]
  describe 'get_taxes test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_tax_by_id
  # 
  # update a single tax based on the ID supplied
  # @param id ID of tax to update
  # @param tax Tax to add to the store
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2012]
  describe 'update_tax_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_tax_by_id_0
  # 
  # update a single tax based on the ID supplied
  # @param id ID of tax to update
  # @param tax Tax to add to the store
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2012]
  describe 'update_tax_by_id_0 test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
