=begin
#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::InlineResponse2001Meta
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InlineResponse2001Meta' do
  before do
    # run before each test
    @instance = SwaggerClient::InlineResponse2001Meta.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InlineResponse2001Meta' do
    it 'should create an instance of InlineResponse2001Meta' do
      expect(@instance).to be_instance_of(SwaggerClient::InlineResponse2001Meta)
    end
  end
  describe 'test attribute "total"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

