=begin
#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.0-SNAPSHOT

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/attribute'
require 'swagger_client/models/attribute_options'
require 'swagger_client/models/brand'
require 'swagger_client/models/category'
require 'swagger_client/models/customer'
require 'swagger_client/models/default_response'
require 'swagger_client/models/i18n'
require 'swagger_client/models/i18n_product'
require 'swagger_client/models/i18n_product_seo'
require 'swagger_client/models/inline_response_200'
require 'swagger_client/models/inline_response_200_1'
require 'swagger_client/models/inline_response_200_1_meta'
require 'swagger_client/models/inline_response_200_2'
require 'swagger_client/models/inline_response_200_3'
require 'swagger_client/models/inline_response_200_4'
require 'swagger_client/models/inline_response_200_5'
require 'swagger_client/models/inline_response_200_6'
require 'swagger_client/models/inline_response_201'
require 'swagger_client/models/inline_response_201_1'
require 'swagger_client/models/inline_response_201_2'
require 'swagger_client/models/inline_response_201_3'
require 'swagger_client/models/inline_response_201_4'
require 'swagger_client/models/meta_partial_response'
require 'swagger_client/models/not_found_response'
require 'swagger_client/models/options'
require 'swagger_client/models/order'
require 'swagger_client/models/payment'
require 'swagger_client/models/product'
require 'swagger_client/models/shipping'
require 'swagger_client/models/tax'

# APIs
require 'swagger_client/api/brands_api'
require 'swagger_client/api/categories_api'
require 'swagger_client/api/customers_api'
require 'swagger_client/api/orders_api'
require 'swagger_client/api/payments_api'
require 'swagger_client/api/products_api'
require 'swagger_client/api/products_attributes_api'
require 'swagger_client/api/shippings_api'
require 'swagger_client/api/taxes_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
